# Default values for go-microservice.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

productionSlot: green
region: eu-west-1
bucket: russ-demo-test
iam_role: go_ms_role

blue:
  replicaCount: 1
  image: 480810688838.dkr.ecr.eu-west-1.amazonaws.com/russ-go-microservice:latest
  pullPolicy: Always
green:
  replicaCount: 1
  image: 480810688838.dkr.ecr.eu-west-1.amazonaws.com/russ-go-microservice:latest
  pullPolicy: Always


service:
  type: ClusterIP
  port: 8080